export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_FAILURE = "USERS_FAILURE";

export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const PATCH_USERS_SUCCESS = "PATCH_USERS_SUCCESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
